version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: skilllane_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - skilllane_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d skilllane_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  skilllane_network:
    driver: bridge
